# Generated by Django 3.1.5 on 2021-07-17 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='주소')),
                ('fee', models.IntegerField(blank=True, verbose_name='회비')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone_num', models.CharField(max_length=12, verbose_name='휴대폰번호')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_care.fitnessclub', verbose_name='소속 헬스장')),
            ],
        ),
    ]
