# Generated by Django 3.1.5 on 2021-07-14 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_care', '0003_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='health_care.fitnessclub', verbose_name='소속 헬스장'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='club',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_care.fitnessclub', verbose_name='소속 헬스장'),
        ),
        migrations.CreateModel(
            name='PersonalTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain', models.DateField(verbose_name='남은 PT 횟수')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PT', to='health_care.member', unique=True, verbose_name='PT회원')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PT', to='health_care.trainer', verbose_name='트레이너')),
            ],
        ),
    ]
