# Generated by Django 3.1.5 on 2021-07-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_care', '0004_auto_20210714_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='라커룸 번호')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker', to='health_care.member', verbose_name='라커룸 주인')),
            ],
        ),
    ]
