# Generated by Django 3.1.5 on 2021-07-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_care', '0005_locker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='기구 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='사용 일시')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_care.equipment', verbose_name='사용 기구')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_care.member', verbose_name='사용자')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.ManyToManyField(related_name='used_equipment', through='health_care.Use', to='health_care.Member', verbose_name='사용자'),
        ),
    ]
